import { projectsMadeType } from "../types/projects.types";

export const openClassroomsProjects: projectsMadeType = [
  {
    title: "[DW] P2: Reservia",
    image: "",
    link: "https://github.com/LePhenix47/LahouitiYounes_2_09012022",
    type: "oc",
    date: new Date("01/09/2022"),
  },
  {
    title: "[DW] P3: ohmyfood",
    image: "",
    link: "https://github.com/LePhenix47/LahouitiYounes_3_26012022-Fix",
    type: "oc",
    date: new Date("01/26/2022"),
  },
  {
    title: "[DW] P4: Agence la Panthère",
    image: "",
    link: "https://github.com/LePhenix47/LahouitiYounes_4_25022022--After",
    type: "oc",
    date: new Date("02/25/2022"),
  },
  {
    title: "[DW] P5: Kanap",
    image: "",
    link: "https://github.com/LePhenix47/LahouitiYounes_5_30032022",
    type: "oc",
    date: new Date("03/30/2022"),
  },
  {
    title: "[DW] P6: Piiquante",
    image: "",
    link: "https://github.com/LePhenix47/LahouitiYounes_6_28042022",
    type: "oc",
    date: new Date("04/28/2022"),
  },
  {
    title: "[DW] P7: Groupomania",
    image: "",
    link: "https://github.com/LePhenix47/LahouitiYounes_7_11052022",
    type: "oc",
    date: new Date("05/11/2022"),
  },
  {
    title: "[JS-React] P4: GameOn",
    image: "",
    link: "https://github.com/LePhenix47/Lahouiti_Younes_4_25092022",
    type: "oc",
    date: new Date("09/25/2022"),
  },
  {
    title: "[JS-React] P6: FishEye",
    image: "",
    link: "https://github.com/LePhenix47/Lahouiti_Younes_6_28092022",
    type: "oc",
    date: new Date("09/28/2022"),
  },
  {
    title: "[JS-React] P7: Les petits plats",
    image: "",
    link: "https://github.com/LePhenix47/Lahouiti_Younes_7_16102022",
    type: "oc",
    date: new Date("10/16/2022"),
  },
  {
    title: "[JS-React] P9: Bill",
    image: "",
    link: "https://github.com/LePhenix47/Lahouiti_Younes_9_06112022--Fix",
    type: "oc",
    date: new Date("11/06/2022"),
  },
  {
    title: "[JS-React] P11: Kasa",
    image: "",
    link: "https://github.com/LePhenix47/Lahouiti_Younes_11_20122022",
    type: "oc",
    date: new Date("12/20/2022"),
  },
  {
    title: "[JS-React] P12: SportSee",
    image: "",
    link: "https://github.com/LePhenix47/Lahouiti_Younes_12_01012023",
    type: "oc",
    date: new Date("01/01/2023"),
  },
  {
    title: "[JS-React] P13: ArgentBank",
    image: "",
    link: "https://github.com/LePhenix47/Lahouiti_Younes_13_26012023",
    type: "oc",
    date: new Date("01/26/2023"),
  },
  {
    title: "[JS-React] P14: HRnet",
    image: "",
    link: "https://github.com/LePhenix47/Lahouiti_Younes_14_06022023",
    type: "oc",
    date: new Date("02/06/2023"),
  },
];

export const personalProjects: projectsMadeType = [
  {
    title: "Password generator",
    image: "",
    link: "https://github.com/LePhenix47/Password-generator_Younes-Lahouiti",
    type: "personal",
    date: new Date("08/19/2022"),
  },
  {
    title: "Customizeable linear gradient",
    image: "",
    link: "https://github.com/LePhenix47/Customizable-linear-gradiant_Younes-Lahouiti",
    type: "personal",
    date: new Date("08/01/2022"),
  },
  {
    title: "Custom video player",
    image: "",
    link: "https://github.com/LePhenix47/Custom-video-player_Younes-Lahouiti---Fix",
    type: "personal",
    date: new Date("29/06/2022"),
  },
  {
    title: "Custom audio player",
    image: "",
    link: "https://github.com/LePhenix47/Custom-audio-player_Younes-Lahouiti",
    type: "personal",
    date: new Date("04/08/2022"),
  },
  {
    title: "Weather app",
    image: "",
    link: "https://github.com/LePhenix47/Weather-app_Younes-Lahouiti",
    type: "personal",
    date: new Date("08/08/2022"),
  },
  {
    title: "Random quiz",
    image: "",
    link: "https://github.com/LePhenix47/Random-quiz_Younes-Lahouiti",
    type: "personal",
    date: new Date("17/09/2022"),
  },
  {
    title: "Unit converter",
    image: "",
    link: "https://github.com/LePhenix47/Unit-converter_Younes-Lahouiti",
    type: "personal",
    date: new Date("20/09/2022"),
  },
  {
    title: "Slider carousel",
    image: "",
    link: "https://github.com/LePhenix47/Slider-carousel_Younes-Lahouiti",
    type: "personal",
    date: new Date("16/09/2022"),
  },
  {
    title: "Filterable list",
    image: "",
    link: "https://github.com/LePhenix47/Filterable-list_Younes-Lahouiti",
    type: "personal",
    date: new Date("14/09/2022"),
  },
  {
    title: "Memory card game",
    image: "",
    link: "https://github.com/LePhenix47/Memory-card-game_Younes-Lahouiti",
    type: "personal",
    date: new Date("05/09/2022"),
  },
  {
    title: "Cookie creator",
    image: "",
    link: "https://github.com/LePhenix47/Cookie-creator_Younes-Lahouiti",
    type: "personal",
    date: new Date("08/09/2022"),
  },
  {
    title: "Pomodoro app",
    image: "",
    link: "https://github.com/LePhenix47/Pomodoro-app_Younes-Lahouiti",
    type: "personal",
    date: new Date("02/09/2022"),
  },
  {
    title: "Infinite scroll",
    image: "",
    link: "https://github.com/LePhenix47/Infinite-scroll__Younes-Lahouiti",
    type: "personal",
    date: new Date("24/08/2022"),
  },
  {
    title: "Calculator app",
    image: "",
    link: "https://github.com/LePhenix47/Calculator-app_Younes-Lahouiti",
    type: "personal",
    date: new Date("15/08/2022"),
  },
  {
    title: "Animated page",
    image: "",
    link: "https://github.com/LePhenix47/Animated-page_Younes-Lahouiti",
    type: "personal",
    date: new Date("05/08/2022"),
  },
  {
    title: "Tic-tac-toe game",
    image: "",
    link: "https://github.com/LePhenix47/Tic-tac-toe-game_Younes-Lahouiti",
    type: "personal",
    date: new Date("02/08/2022"),
  },
];

export const professionalProjects: projectsMadeType = [
  {
    title: "Californie Gym (coming soon)",
    image: "",
    link: "",
    type: "professional",
    date: new Date("02/11/2022"),
  },
  {
    title: "SFCC delivery library",
    image: "",
    link: "",
    type: "professional",
    date: new Date("02/11/2022"),
  },
];

export const npmProjects: projectsMadeType = [
  {
    title: "Timeout utility",
    image: "",
    link: "https://github.com/LePhenix47/Timout-utility_npm-package",
    type: "npm",
    date: new Date("02/09/2023"),
  },
  {
    title: "Interval utility",
    image: "",
    link: "https://github.com/LePhenix47/Interval-utility_npm-package",
    type: "npm",
    date: new Date("02/09/2023"),
  },
  {
    title: "Cookies utility",
    image: "",
    link: "https://github.com/LePhenix47/Cookie-utility_npm-package",
    type: "npm",
    date: new Date("02/09/2023"),
  },
  {
    title: "WebStorage utility",
    image: "",
    link: "https://github.com/LePhenix47/WebStorage-utility_npm-package",
    type: "npm",
    date: new Date("02/09/2023"),
  },
  {
    title: "React Data table",
    image: "",
    link: "https://www.npmjs.com/package/@lephenix47/react-datatable",
    type: "npm",
    date: new Date("02/06/2023"),
  },
];
